### ISSUE TITLE
How to retrain this squeezeNet to some other classes?

### ISSUE THREAD

**Issue by WuXinyang2012** [appinho/SqueezeNet#1]
Hi thanx for your code! In my case, I want to retrain this Network to only classify around 20 classes of fruits and vegetables since I am going to embed my Raspberry Pi into one Smart Kitchen system. So I dont want it to classify around 1000 classes in ImageNet but only focus on the 20 classes of fruits and vegetables. Can you teach me how to make it? Thanks!

**Comment by appinho** [comment]
Look into transfer learning.
Also get labeled data of your fruits and vegetables.
Then I could help you out of feed you with more information :)

2018-03-30 19:39 GMT+02:00 Wu Xinyang <notifications@github.com>:
